name: Sequential Pipeline

on:
  workflow_dispatch:
    inputs:
      run_test:
        description: 'Run test stage'
        type: boolean
        required: true
        default: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Build
        run: echo "Running build step"
      
      - name: Save build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: .

  test:
    needs: build
    if: github.event.inputs.run_test == true
    runs-on: ubuntu-latest
    environment:
      name: test
      url: https://test.example.com
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: build-artifacts
      
      - name: Run tests
        run: echo "Running tests"
