name: Deployment Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: echo "Building application"
      - name: Save artifacts
        uses: actions/upload-artifact@v3
        with:
          name: app-artifacts
          path: .
          retention-days: 5

  wait-for-staging-approval:
    needs: build
    runs-on: ubuntu-latest
    environment: staging-approval
    steps:
      - run: echo "Approved for staging deployment"

  deploy-staging:
    needs: wait-for-staging-approval
    runs-on: ubuntu-latest
    environment:
      name: staging
      url: https://staging.example.com
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: app-artifacts
      - name: Deploy to staging
        run: echo "Deploying to staging"

  wait-for-production-approval:
    needs: deploy-staging
    runs-on: ubuntu-latest
    environment: production-approval
    steps:
      - run: echo "Approved for production deployment"

  deploy-production:
    needs: wait-for-production-approval
    runs-on: ubuntu-latest
    environment:
      name: production
      url: https://production.example.com
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: app-artifacts
      - name: Deploy to production
        run: echo "Deploying to production"