name: Deployment Pipeline

on:
  # Trigger build on push to master
  push:
    branches:
      - master
  # Manual triggers for deployments
  workflow_dispatch:
    inputs:
      stage:
        description: 'Deployment stage'
        required: true
        type: choice
        options:
          - stage
          - prod

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Build
        run: echo "Building application"
        
      - name: Save artifacts
        uses: actions/upload-artifact@v3
        with:
          name: app-artifacts
          path: .

  deploy-stage:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: staging
      url: https://staging.example.com
    if: github.event_name == 'workflow_dispatch' && github.event.inputs.stage == 'stage'
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: app-artifacts
          
      - name: Deploy to staging
        run: echo "Deploying to staging"

  deploy-prod:
    needs: [build, deploy-stage]
    runs-on: ubuntu-latest
    environment:
      name: production
      url: https://production.example.com
    if: github.event_name == 'workflow_dispatch' && github.event.inputs.stage == 'prod'
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: app-artifacts
          
      - name: Deploy to production
        run: echo "Deploying to production"